### ISSUE TITLE
Add format string to plots

### ISSUE THREAD

**Issue by bjorksteinsson** [pothosware/pothos-widgets#32]
Plot titling would be better if it could be format stringed.

"Constellation: %1" <--- BPSK or QPSK.

**Comment by guruofquality** [comment]
This may seem contrived, but how-about a formatter block with a slot for arbitrary input and a signal for a formatted string? you would use it like this:

drop down [labelChanged] -> [arg]formatter[valueChanged] -> [setTitle]Constellation

**Comment by guruofquality** [comment]
With the evaluator block its possible to take the signal from the GUI control and append to it:

```
Evaluator expression: "Constellation: "//value
```

The evaluator’s trigger signal can be used to set the plot's title.
