### ISSUE TITLE
Really cool frequency entry widget

### ISSUE THREAD

**Issue by guruofquality** [pothosware/pothos-widgets#37]
One of those widgets with hooks to spin individual digits up and down (example gqrx)

**Comment by pavel-demin** [comment]
I have one small frequency widget that looks like similar to SDR#:

**Comment by guruofquality** [comment]
@pavel-demin Thanks BTW, I'd like to give it a shot. What's the license/copyright on this code, if I were to copy it into pothos-widgets, I would like to properly attribute it.

**Comment by pavel-demin** [comment]
> What's the license/copyright on this code

I think that it's OK to make it BSL-1.0 as other pothos-widgets.

Geometry of this widget could be improved. It's defined in [Indicator::Indicator](https://github.com/pavel-demin/MiniTRX/blob/QtWidgets/client/indicator.cpp#L85) and it's fixed size in the current version. If you're interested, I can rewrite it using layouts and spacers.

Here is how it looks like:
![indicator](https://cloud.githubusercontent.com/assets/8037893/16186259/c4582274-36c9-11e6-8ed4-f48c8a1fdf09.png)

**Comment by pavel-demin** [comment]
I've updated the geometry and removed all the hard-coded values.

The minimum working code should look like the following:
```
  m_IndicatorRX = findChild<Indicator *>("IndicatorRX");
  m_IndicatorRX->setSize(8);
  m_IndicatorRX->setValueMin(0);
  m_IndicatorRX->setValueMax(50000000);
  m_IndicatorRX->setValue(600000);
  m_IndicatorRX->setFrameShape(QFrame::Panel);
  m_IndicatorRX->setFrameShadow(QFrame::Sunken);
  connect(m_IndicatorRX, SIGNAL(valueChanged(int)), this, SLOT(on_IndicatorRX_changed(int)));
```

**Comment by guruofquality** [comment]
I made a branch to play around with this: https://github.com/pothosware/pothos-widgets/tree/digital_spinner

A few comments:
* I found that void resizeEvent(QResizeEvent *event) gets stuck in a loop expanding until the screen explodes. At least in this case, setFont() causes additional resize events and ever growing due to ```f.setPixelSize(height());```. Whats the desired behaviour here when setting the font height on resize?
* I noticed that the value is stored as a signed integer. It seems like long long would be more desirable to handle a frequency in Hz beyond (1 << 31) or 2.147483648e9

**Comment by pavel-demin** [comment]
> I found that void resizeEvent(QResizeEvent *event) gets stuck in a loop expanding until the screen explodes.

I've tried to fix this problem by replacing setPixelSize() with setPointSizeF() in https://github.com/pothosware/pothos-widgets/commit/a33ba626a2fcc3a1ab099185840a144a70675d44.

> Whats the desired behaviour here when setting the font height on resize?

The main idea is to scale digits when widget is resized. Each digit is a QLabel. By default, QLabel doesn't scale the text font size when it's resized. resizeEvent() implements this functionality.

**Comment by pavel-demin** [comment]
> I noticed that the value is stored as a signed integer. It seems like long long would be more desirable to handle a frequency in Hz beyond (1 << 31) or 2.147483648e9

Replaced int with qint64 in https://github.com/pothosware/pothos-widgets/commit/73a4de5c22747d68e9b2c09564272e79b487c407.

**Comment by guruofquality** [comment]
@pavel-demin  thanks for the additions! its basically working. A few oddities:

![http://i.imgur.com/yNMgl7I.png](http://i.imgur.com/yNMgl7I.png)

* In the top most widget, adding digits while its resized seems to insert them very small and not matching the size of the other digits. I think the digits needs to be sized to match the parent when added. 
* In the middle widget, sometimes the resize events dont get to all of the digits consistently and they end up with different sizes. I think the resize event should be in the parent and apply equal height to all digits. I think this ends up being the same fix as the first issue mentioned
* And the last one, I set 10 digits, and a max of 4.4e9. So the largest digit is initially black after setting it and then goes to gray upon clicking on the box. I just wondered if that was the intention. it looks like unused upper digits are supposed to go gray, but perhaps it should be when the quotient is 0 and the digit is non zero?

**Comment by pavel-demin** [comment]
I've tried to fix the automatic font scaling but without much success. I propose a solution with manually controlled font size. It's in https://github.com/pothosware/pothos-widgets/commit/0eb8e3b48252b85b613282271f89031191485185. What do you think?

**Comment by guruofquality** [comment]
That works for me. And I think everything looks pretty good. Perhaps the automatic scaling can be revisited in the future and for other widgets as well.

I ended up renaming the widget to odometer. I really don't know what the widget community calls these things, but it seems to work just like the odometer dials inside a car's speedometer. Hope that makes sense.

One more thing. Can you put some kind of license+copyright text in the indicator sources? Any format is fine, just include copyright holder, year, and some permissive license that you like.

Example:
```
// Copyright (C) 2016  Pavel Demin
// SPDX-License-Identifier: BSL-1.0
```

**Comment by pavel-demin** [comment]
> Can you put some kind of license+copyright text in the indicator sources?

OK. Done.

> And the last one, I set 10 digits, and a max of 4.4e9. So the largest digit is initially black after setting it and then goes to gray upon clicking on the box.

I noticed similar glitches with the previous auto-scaling version. I can't reproduce them with the latest version. So, I'm not sure if it's fixed or not.

**Comment by guruofquality** [comment]
> I noticed similar glitches with the previous auto-scaling version. I can't reproduce them with the latest version. So, I'm not sure if it's fixed or not.

I think I figured it out. It seems like palette is not a good way to set the color, stylesheet should be used
http://stackoverflow.com/questions/2749798/qlabel-set-color-of-text-and-background

Perhaps the c_StyleSheets should be parametrized (``color : %1``) with the current label text color. The setValue() would just set the digit's m_Color and reapply the style sheet. Each set stylesheet call would be like:

```
setStyleSheet(c_StyleSheets[1].arg(m_Color));
```

**Comment by guruofquality** [comment]
I took a whack at the color issue. This fixes the problem and cleans things up a bit as well. I hope thats ok. Feel free to upstream these changes: https://github.com/pothosware/pothos-widgets/commit/2768a5cf111bf9a7b87721442aa8f7ded49314c7

**Comment by pavel-demin** [comment]
Nice solution. The code looks cleaner now.
